defaults: &defaults
  working_directory: /home/circleci/app
  docker:
    - image: circleci/node:8.11.1

restore-cache: &restore-cache
  name: Restore Yarn Package Cache
  keys:
    - v3-yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
    - v3-yarn-packages-{{ .Branch }}-
    - v3-yarn-packages-master-
    - v3-yarn-packages-

version: 2
jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          <<: *restore-cache
      - run:
          name: Install Dependencies
          command: yarn
      - save_cache:
          name: Save Yarn Package Cache
          key: v3-yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules/
            - ~/.cache/Cypress
  lint:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          <<: *restore-cache
      - run:
          name: Code Lint
          command: yarn ci:lint
  build:
    <<: *defaults
    environment:
      - BABEL_ENV: test
    steps:
      - checkout
      - restore_cache:
          <<: *restore-cache
      - run:
          name: Build Application
          command: yarn ci:build
      - persist_to_workspace:
          root: .
          paths: public
  unit-tests:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          <<: *restore-cache
      - run:
          name: Unit Tests
          command: yarn ci:unit-tests
  feature-tests:
    <<: *defaults
    docker:
      - image: cypress/base:8
    steps:
      - checkout
      - attach_workspace:
          at: .
      - restore_cache:
          <<: *restore-cache
      - run:
          name: Symlink Cypress Cache
          command: |
            mkdir -p /root/.cache
            ln -s /home/circleci/.cache/Cypress /root/.cache/Cypress
      - run:
          name: Start application server
          command: yarn ci:start-server
          background: true
      - run:
          name: Feature Tests
          command: yarn ci:feature-tests

workflows:
  version: 2
  build-and-test:
    jobs:
      - install
      - lint:
          requires:
            - install
      - build:
          requires:
            - install
      - unit-tests:
          requires:
            - install
      - feature-tests:
          requires:
            - build
